version: '3.8'

networks:
  proxy:
    name: swilink

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: /bin/sh -c "npm install && npm run dev"
    depends_on:
      - mongodb
    networks:
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - proxy

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - proxy